project:
  type: website
  output-dir: docs
  # post-render: 
   # - "cp -rnv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352

website:
  title: "Ahmed Osman"
  site-url: https://ahmedmoosman.github.io
  description: "Research Assistant"
  favicon: assets/essentials/img/logo.png
  comments: 
    utterances: 
      repo: ahmedmoosman/ahmedmoosman.github.io
      label: utterances
      theme: body-light
      issue-term: title 
 
  navbar:
    logo: assets/essentials/img/logo.png
    tools:
    - icon: github
      href: https://www.github.com/ahmedmoosman/ahmedmoosman.github.io
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "Meeting People Where They R"
        href: blog/index.qmd
      - text: Talks
        aria-label: "Invited Talks"
        href: talk/index.qmd  
      - text: Research
        aria-label: "Publications"
        href: publication/index.qmd
      - text: Portfolio
        aria-label: "Project Portfolio"
        href: portfolio/index.qmd
  
  page-footer:  
    left: >-
     &#169; 2025 Ahmed Osman &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://x.com/ahmed_ainaan" title="X" target="_blank" rel="noopener">{{< fa brands square-x-twitter >}}</a>
      <a class="link-dark me-1" href="https://bsky.app/profile/ainaan.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a>
      <a class="link-dark me-1" href="https://github.com/ahmedmoosman" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://linkedin.com/in/ahmed-osman-6371aa12a/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://econtwitter.net/@ahmed6657" title="mastodon" target="_blank" rel="noopener">{{< fa brands mastodon >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0009-0000-2328-0496" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
    right: 
     <span class="faux-block">[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>


format: 
  html:
    theme:
      light:
        - cosmo
        # - superhero
        - assets/silvia-theme.scss
        - assets/essentials/colors.scss
        - assets/essentials/fonts.scss
    highlight-style: a11y

execute: 
  freeze: auto